version: "3.9"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: night_navigator_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: night_navigator
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data

volumes:
  postgis_data:
